skip_tags: true

os: Visual Studio 2015

services:
  - postgresql96

environment:
  global:
    PGINSTALLATION: "C:\\Program Files\\PostgreSQL\\9.6\\bin"
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

build_script:
  - "PATH=C:\\Program Files\\PostgreSQL\\9.6\\bin\\;%PATH%"
  - "which pg_config"
  - "pg_config --version"
  - "git --no-pager log -n2"
  - "echo %APPVEYOR_REPO_COMMIT%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -Ur test-requirements.txt"
  - "pip install codecov"

test_script:
  - "mkdir empty"
  - "cd empty"
  # Make sure it's being imported from where we expect
  - "python -c \"import os, triopg; print(os.path.dirname(triopg.__file__))\""
  - "python -u -m pytest -W error -ra -v -s --pyargs triopg --cov=triopg --cov-config=../.coveragerc"
  - "codecov"
